version: '2'
services:
  hadoop-master:
    extends:
      service: java-8-base
    image: '${HADOOP_BASE_IMAGE}:${DOCKER_IMAGES_VERSION}'
    hostname: hadoop-master
    ports:
      - '${HIVE_PROXY_PORT}:1180'
      - '5006:5006'
      - '8020:8020'
      - '8042:8042'
      - '8088:8088'
      - '9000:9000'
      - '9083:9083' # Metastore Thrift
      - '9864:9864' # DataNode Web UI since Hadoop 3
      - '9870:9870' # NameNode Web UI since Hadoop 3
      - '10000:10000' # HiveServer2
      - '19888:19888'
      - '50070:50070' # NameNode Web UI prior to Hadoop 3
      - '50075:50075' # DataNode Web UI prior to Hadoop 3
    volumes:
      - ../../../../presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/avro:/docker/presto-product-tests/avro
